<?xml version="1.0"?>
<!-- Originally from https://github.com/mit-racecar/racecar_simulator/blob/master/racecar.xacro -->
<!-- A simple model of the racecar for rviz -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">


  <!-- GEOMETRY PARAMS -->
  <xacro:property name="wheelbase" value="0.325" />
  <xacro:property name="width" value="0.2" />
  <xacro:property name="height" value="0.1" />
  <xacro:property name="ground_offset" value="0.04" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_length" value="0.045" />
  <xacro:property name="laser_distance_from_base_link" value="0.275" />
  <xacro:property name="laser_height" value="0.05" />
  <xacro:property name="laser_radius" value="0.026" />

  <!-- ISAAC GYM RIGID BODY PARAMS -->
  <!-- Wheel Properties -->
  <xacro:property name="wheel_mass" value=".5" />
  <xacro:property name="wheel_joint_props">
    <axis xyz="0 1 0"/>
  </xacro:property>
  <xacro:property name="wheel_inertia">
    <inertia ixx="0.0013" ixy="0" ixz="0" iyy="0.0024" iyz="0" izz="0.0013"/>
  </xacro:property>

  <!-- Hinge Properties -->
  <xacro:property name="hinge_mass" value="0.01" />
  <xacro:property name="hinge_joint_props">
    <axis xyz="0 0 1"/>
    <limit lower="${-1 * pi / 6}" upper="${pi / 6}" effort="1000" velocity="1.0"/>
  </xacro:property>

  <!-- Chassis Properties -->
  <xacro:property name="chassis_mass" value="10" />
  <xacro:property name="chassis_inertia">
    <inertia
      ixx="1"
      ixy="0"
      ixz="0"
      iyy="1"
      iyz="0"
      izz="1"
    />
  </xacro:property>

  <!-- Sensor Properties -->
  <xacro:property name="laser_mass" value=".01" />

  <material name="black">
    <color rgba="0.2 0.2 0.2 1."/>
  </material>

  <material name="blue">
    <color rgba="0.3 0.57 1. 1."/>
  </material>

  <!-- MACROS -->
  <xacro:macro name="wheel_block" params="name">
    <link name="${name}">
      <xacro:visual_collision_block>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        <container>
          <material name="black"/>
          <origin rpy="${pi/2} 0 0"/>
        </container>
      </xacro:visual_collision_block>
      <xacro:inertial_block mass="${wheel_mass}">
        <container>
          <xacro:insert_block name="wheel_inertia"/>
        </container>
      </xacro:inertial_block>
    </link>
  </xacro:macro>

  <xacro:macro name="inertial_block" params="mass **kwargs">
    <inertial>
      <mass value="${mass}"/>
      <xacro:insert_block name="kwargs"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="visual_collision_block" params="*geometry **kwargs">
    <visual>
      <geometry>
        <xacro:insert_block name="geometry"/>
      </geometry>
      <xacro:insert_block name="kwargs"/>
    </visual>
    <collision>
      <geometry>
        <xacro:insert_block name="geometry"/>
      </geometry>
      <xacro:insert_block name="kwargs"/>
    </collision>
  </xacro:macro>

  <!-- MAIN FILE -->
  <link name="chassis">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <!-- <collision>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
    </collision> -->
    <xacro:inertial_block mass="${chassis_mass}">
      <container>
        <xacro:insert_block name="chassis_inertia"/>
        <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      </container>
    </xacro:inertial_block>
  </link>

  <joint name="chassis_to_laser_model" type="fixed">
    <parent link="chassis"/>
    <child link="laser_model"/>
    <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(laser_height/2)}"/>
  </joint>

  <link name="laser_model">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <xacro:inertial_block mass="${laser_mass}"><container/></xacro:inertial_block>
  </link>

  <joint name="chassis_to_back_left_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${(wheel_length+width)/2} ${wheel_radius}"/>
    <xacro:insert_block name="wheel_joint_props"/>
  </joint>

  <xacro:wheel_block name="back_left_wheel"/>

  <joint name="chassis_to_back_right_wheel" type="continuous">
    <parent link="chassis"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${-(wheel_length+width)/2} ${wheel_radius}"/>
    <xacro:insert_block name="wheel_joint_props"/>
  </joint>

  <xacro:wheel_block name="back_right_wheel"/>

  <joint name="chassis_to_front_left_hinge" type="revolute">
    <parent link="chassis"/>
    <child link="front_left_hinge"/>
    <origin xyz="${wheelbase} ${(wheel_length+width)/2} ${wheel_radius}"/>
    <xacro:insert_block name="hinge_joint_props"/>
  </joint>

  <link name="front_left_hinge">
    <xacro:inertial_block mass="${hinge_mass}"><container/></xacro:inertial_block>
  </link>


  <joint name="front_left_hinge_to_wheel" type="continuous">
    <parent link="front_left_hinge"/>
    <child link="front_left_wheel"/>
    <xacro:insert_block name="wheel_joint_props"/>
  </joint>

  <xacro:wheel_block name="front_left_wheel"/>

  <joint name="chassis_to_front_right_hinge" type="revolute">
    <parent link="chassis"/>
    <child link="front_right_hinge"/>
    <origin xyz="${wheelbase} ${-(wheel_length+width)/2} ${wheel_radius}"/>
    <xacro:insert_block name="hinge_joint_props"/>
  </joint>

  <link name="front_right_hinge">
     <xacro:inertial_block mass="${hinge_mass}"><container/></xacro:inertial_block>
  </link>

  <joint name="front_right_hinge_to_wheel" type="continuous">
    <parent link="front_right_hinge"/>
    <child link="front_right_wheel"/>
    <xacro:insert_block name="wheel_joint_props"/>
  </joint>

  <xacro:wheel_block name="front_right_wheel"/>

</robot>
